#!/bin/bash
docker build -t mtsev/rubikbot .

echo Delete old container...
docker rm -f rubikbot

echo Run new container...
docker run -d \
	--name rubikbot \
	--restart=always \
	mtsev/rubikbot
